export const SET_INITIAL_STATE = "SET_INITIAL_STATE";
export const SET_INITIAL_STATE_START = "SET_INITIAL_STATE_START";
export const SET_INITIAL_STATE_FAIL = "SET_INITIAL_STATE_FAIL";
export const ON_STORE_SPENDING = "ON_STORE_SPENDING";
export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const TOGGLE_LOADING = "TOGGLE_LOADING";
export const ON_BUDGET_INPUT_CHANGED = "ON_BUDGET_INPUT_CHANGED";

export const ON_LOGIN = "ON_LOGIN";
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
