export const SET_INITIAL_STATE = 'SET_INITIAL_STATE';
export const FETCH_DATA_START = 'FETCH_DATA_START';
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL';
export const ON_STORE_SPENDING = 'ON_STORE_SPENDING';
export const ON_STORE_SPENDING_SUCCESS = 'ON_STORE_SPENDING_SUCCESS';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';
export const ON_BUDGET_INPUT_CHANGED = 'ON_BUDGET_INPUT_CHANGED';
export const ON_SPENDING_INPUT_CHANGED = 'ON_SPENDING_INPUT_CHANGED';
export const ON_STORE_BUDGET = 'ON_STORE_BUDGET';

export const ON_LOGIN = 'ON_LOGIN';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const CONFIRM_ERROR = 'CONFIRM_ERROR';
export const CONFIRM_AUTH_ERROR = 'CONFIRM_AUTH_ERROR';
