export const SET_INITIAL_STATE = "SET_INITIAL_STATE";
export const ON_STORE_SPENDING = "ON_STORE_SPENDING";
export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const TOGGLE_LOADING = "TOGGLE_LOADING";
export const ON_BUDGET_INPUT_CHANGED = "ON_BUDGET_INPUT_CHANGED";
